services:
  vector-db:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333" 
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
